// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayDayExplosion.Infrastructure.Persistence;

#nullable disable

namespace PayDayExplosion.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828184037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.PayCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PayCategories");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.PayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PayTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SpanDetailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpanDetailTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SpanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OvertimeFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("RegularFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id");

                    b.ToTable("SpanTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.Subspan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClockedHours")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Factor1")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Factor2")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Factor3")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Factor4")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSchedule")
                        .HasColumnType("bit");

                    b.Property<decimal>("MealHours")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("SpanDetailTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SpanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubTimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubTimeOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubspanDetailTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Substract")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("WorkshiftTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayCategoryId");

                    b.HasIndex("SpanDetailTypeId");

                    b.HasIndex("SubspanDetailTypeId");

                    b.HasIndex("WorkshiftTypeId");

                    b.ToTable("Subspans");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SubspanDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubspanDetailTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SubspanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubspanDetailTypeId");

                    b.HasIndex("SubspanId");

                    b.ToTable("SubspanDetails");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SubspanDetailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubspanDetailTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.WorkdayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkdayTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.WorkshiftType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OvertimeFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("RegularFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id");

                    b.ToTable("WorkshiftTypes");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.Subspan", b =>
                {
                    b.HasOne("PayDayExplosion.Domain.Data.Entities.PayCategory", "PayCategory")
                        .WithMany("Subspans")
                        .HasForeignKey("PayCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayDayExplosion.Domain.Data.Entities.SpanDetailType", null)
                        .WithMany("Subspans")
                        .HasForeignKey("SpanDetailTypeId");

                    b.HasOne("PayDayExplosion.Domain.Data.Entities.SubspanDetailType", null)
                        .WithMany("Subspans")
                        .HasForeignKey("SubspanDetailTypeId");

                    b.HasOne("PayDayExplosion.Domain.Data.Entities.WorkshiftType", "WorkshiftType")
                        .WithMany("Subspans")
                        .HasForeignKey("WorkshiftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayCategory");

                    b.Navigation("WorkshiftType");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SubspanDetail", b =>
                {
                    b.HasOne("PayDayExplosion.Domain.Data.Entities.SubspanDetailType", "SubspanDetailType")
                        .WithMany("SubspanDetails")
                        .HasForeignKey("SubspanDetailTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayDayExplosion.Domain.Data.Entities.Subspan", "Subspan")
                        .WithMany("SubspanDetails")
                        .HasForeignKey("SubspanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subspan");

                    b.Navigation("SubspanDetailType");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.PayCategory", b =>
                {
                    b.Navigation("Subspans");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SpanDetailType", b =>
                {
                    b.Navigation("Subspans");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.Subspan", b =>
                {
                    b.Navigation("SubspanDetails");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.SubspanDetailType", b =>
                {
                    b.Navigation("SubspanDetails");

                    b.Navigation("Subspans");
                });

            modelBuilder.Entity("PayDayExplosion.Domain.Data.Entities.WorkshiftType", b =>
                {
                    b.Navigation("Subspans");
                });
#pragma warning restore 612, 618
        }
    }
}
